apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: python-web
          image: REPLACE_WITH_ARTIFACT_REGISTRY_IMAGE
          ports:
            - containerPort: 5000
